favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    ## Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/wohub']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    #- ['AngryPowman', 'This is a link', 'http://powman.org']
    - ['hexo-theme-prontera', 'blog`s theme', 'http://powman.org']


# About
about_info:
    name: "会上树的猪"
    bio: "想想干点啥"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: angrypowman
duoshuo: 

# Analytics
google_analytics: angrypowman
tencent_analytics: 
 
# Copyright Infomation
startyear: 2019
